import About from "@/components/About";
import Follow from "@/components/Follow";
import Hero from "@/components/Hero";
import Menu from "@/components/Menu";
import Order from "@/components/Order";
import Special from "@/components/Special";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <About />
        <Menu />
        <Special />
        <Order />
        <Follow />
      </main>
    </>
  );
}
